export const homeObjOne = {
  id: "about_me",
  className: "about_me_class",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "About Me",
  headLine: "",
  description:
    "Hi, I'm Andreas. A geologist turned full stack web developer, I am fully immersed in building web applications. This webpage showcases some of my projects. My main focus is javascript and the MERN stack. Recently I've developed an interest in distributed apps (dapps) and in writing smart contracts with solidity on the ethereum blockchain. I never stop learning and building and every new project is a much welcome challenge to be tackeled with enthusiasm and in a goal-driven and target-oriented fashion.",
  buttonLabel: "Go to projects",
  buttonTarget: "/web_shop",
  imgStart: false,
  img: require("../../images/svg-1.svg").default,
  alt: "web development",
  dark: true,
  primary: true,
  darkText: true,
};

export const homeObjTwo = {
  id: "web_shop",
  className: "web_shop_class",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Project No 1",
  headLine: "Bicycle Webshop",
  description:
    "This app features some of the most common user facing functionalities that can be found in modern webshop applications. It has been build using the MERN tech stack.",
  teckStackHeader: "Frameworks and Libraries:",
  teckStack: "React.js, Redux, Node.js, Express, MongoDB",
  buttonLabel: "open in tab",
  buttonExternalTarget: "https://mern-stack-example-webshop.herokuapp.com/",
  imgStart: true,
  url: "https://mern-stack-example-webshop.herokuapp.com/",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjThree = {
  id: "sliding_puzzle",
  className: "sliding_puzzle_class",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Project No 2",
  headLine: "Sliding Puzzle",
  description:
    "This little application challenges its users to slide each piece of the puzzle back in the correct position. Players can choose between numbers or a selection of images.",
  teckStackHeader: "Frameworks and Libraries:",
  teckStack: "React.js",
  buttonLabel: "see the code",
  buttonExternalTarget: "https://github.com/akoeth-portfolio/sliding-puzzle",
  imgStart: false,
  url: "https://puzzle-react.herokuapp.com/",
  dark: false,
  primary: false,
  darkText: true,
};

export const homeObjFour = {
  id: "tic_tac_toe",
  className: "tic_tac_toe_class",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Project No 3",
  headLine: "Tic Tac Toe Chat",
  description:
    "A classic implementation of the good old tic tac toe principle, this application enables its users to play against each other while having a little chat.",
  teckStackHeader: "Frameworks and Libraries:",
  teckStack: "Node.js, Express, Socket io",
  buttonLabel: "see the code",
  buttonExternalTarget: "https://github.com/akoeth-portfolio/tic-tac-toe",
  imgStart: true,
  url: "https://tic-tac-toe-web-s.herokuapp.com/",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjFive = {
  id: "blockchain",
  className: "blockchain_class",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Project No 4",
  headLine: "Blockchain",
  description:
    "This app showcases some of the functionalities a blockchain has. By no means comprehensive, it nonetheless offers a tiny glimpse into the rapidly emerging world of blockchain technology.",
  teckStackHeader: "Frameworks and Libraries:",
  teckStack: "React.js",
  buttonLabel: "open in tab",
  buttonExternalTarget: "https://blockchain-demo-app.herokuapp.com/",
  imgStart: false,
  url: "https://blockchain-demo-app.herokuapp.com/",
  dark: false,
  primary: false,
  darkText: true,
};
